### ISSUE TITLE
Pascal indents as double spaces

### ISSUE THREAD

**Issue by madorin** [asfernandes/cloop#3]
Now pascal generated code uses tab character (#11) as indents, while pascal coding styles uses two spaces (both in free pascal and commercial versions).

Reference:
http://edn.embarcadero.com/article/10280
http://wiki.freepascal.org/Coding_style

**Comment by asfernandes** [comment]
Do you want me to take serious something that says?

"Don't use spaces around operators, colons, parentheses etc. e.g. write p:=p+i; instead of p := p + i ;."

I'll not generate code indented with spaces, no matter what "standard styles" say, sorry. If you want it, use something external to reformat the code.

**Comment by madorin** [comment]
Eh, it's really annoying to read & understand "Tab" indented code.
Never meet such format. Anyway, Your decision.
